unique_ids:
  assets:
    standard-page.html: CJDV2QBVELAOS333PHC7V6DOQPJK6KOB
    theme.css: PICEBX33DCGQNKMKOI5YQ4GVXTRD5POB
  forms:
    Form1: NW6BE2DEQDG3UMH4HIR4GBALXUUVMRAF
  modules: {}
  scripts: {}
  server_modules: {}
